### ISSUE TITLE
Breakpoints not showing up and not toggling

### ISSUE THREAD

**Issue by Narice** [sakhnik/nvim-gdb#99] opened 2019-12-18 13:25 UTC
When setting breakpoints through :GdbToggleBreakpoint, breakpoints are added correctly but are not toggling meaning that if one exists, it is not deleted. I'm not on a blank line when doing this
Also, no breakpoints are showing up on the file that is displayed when debugging
My guess would be that the breaks variable in breakpoint.py is not set correctly but I can't seem to get the gist of how the breakpoints are queried
I would really love to work on this issue!

**Comment by sakhnik** [comment] 2019-12-21 07:45
I guess that the plugin has a hard time matching `info breakpoint` output with the actual path to the source files. The same happens to me when I build with CMake, but try do debug from a different directory. Unfortunately, GDB doesn't seem to resolve paths to absolute by itself, and only prints them relative to the build directory.
What's your output of `info breakpoints`? Do those paths refer to the actual location of the sources?

**Comment by Narice** [comment] 2019-12-21 11:43
I went to replicate the issue and actually got the following error after typing "start" in the gdb prompt.
![nvim-gdb](https://user-images.githubusercontent.com/31109099/71307428-93ce7500-2431-11ea-9c86-681d2e647064.png)
As it was a new thing going on here, I uninstalled and reinstalled the plugin, but the same problem happens. I'm quite lost now...
I will do a minimal .vimrc to be sure that it is your plugin and not something in my .vimrc that is causing the problem and will keep you updated on the problem.
However, when I had the issue, the execution file and the source file were in the same folder (I was just testing the plugin). I will try to print the breakpoints as soon as I can

**Comment by sakhnik** [comment] 2019-12-21 11:45
Probably, you have to run the command `:UpdateRemotePlugins`

**Comment by sakhnik** [comment] 2020-01-05 21:51
@Narice, any updates on the issue?

**Comment by grifcj** [comment] 2020-01-13 07:49
Landed here after having same symptoms, perhaps with same root cause.

My problem was that the debug info has a relative path (which shows up in the 'info breakpoints' response) and can't be handled by the matching logic

```python lib/gdb_proxy.py
                    is_end_match = last_src.endswith(match.group(1))
                    is_end_match_full_path = \
                        last_src.endswith(os.path.realpath(match.group(1)))
```

See debug trace to make it a bit more clear. At the bottom, you can see that realpath combined with the relative path eliminates the 'test' path component, thus causing a match failure.
```
(Pdb) args
self = <__main__.GdbProxy object at 0x7f69591f1f50>
last_src = '/home/grifcj/.local/share/nvim/plugged/nvim-gdb/test/src/test.cpp'
response = b'server info breakpoints\r\nNum     Type           Disp Enb Address            What\r\n1       breakpoint     keep y   0x00000000000011c0 in Bar(unsigned int) at ../src/test.cpp:5\r\n(gdb) \x1
\x1a\x1a'
(Pdb) p match
<re.Match object; span=(0, 17), match='../src/test.cpp:5'>
(Pdb) p match.group(1)
'../src/test.cpp'
(Pdb) l .
 42                     fields = re.split(r"\s+", line)
 43                     if fields[3] == 'y':    # Is enabled?
 44 B                       match = pattern.fullmatch(fields[-1])   # file.cpp:line
 45                         if not match:
 46                             continue
 47  ->                     is_end_match = last_src.endswith(match.group(1))
 48                         is_end_match_full_path = \
 49                             last_src.endswith(os.path.realpath(match.group(1)))
 50                         if (match and (is_end_match or is_end_match_full_path)):
 51                             line = match.group(2)
 52                             br_id = fields[0]
(Pdb) n
> /home/grifcj/.local/share/nvim/plugged/nvim-gdb/lib/gdb_proxy.py
-> last_src.endswith(os.path.realpath(match.group(1)))
(Pdb) p is_end_match
False
(Pdb) p os.path.realpath(match.group(1))
'/home/grifcj/.local/share/nvim/plugged/nvim-gdb/src/test.cpp'

```

The reason for relative paths is that the ninja generator with cmake uses relative paths when the build directory is a sub directory of source directory. https://gitlab.kitware.com/cmake/cmake/issues/13894. cmake seems to be waiting for a fix in ninja to address that, but the workaround is to use a sibling build directory to get absolute paths for source files (which works as expected). Or you can use the makefile generator which does absolute paths either way. I'm not sure about other generators.

See the build log that preceded the above debug trace, where build directory was made a subdirectory of the test folder in nvim-gdb repo. Ninja performs compilation by using path relative to build directory for source file on command line, and gcc simply passes that along to debug info.
```
$ ninja -C build -v
ninja: Entering directory `build'
[1/2] /usr/bin/c++    -g -MD -MT CMakeFiles/testapp.dir/src/test.cpp.o -MF CMakeFiles/testapp.dir/src/test.cpp.o.d -o CMakeFiles/testapp.dir/src/test.cpp.o -c ../src/test.cpp
[2/2] : && /usr/bin/c++  -g   CMakeFiles/testapp.dir/src/test.cpp.o  -o ../a.out   && :
```

It might be possible to use `info source` command with gdb to get full source path, though not sure if that's reliable all the time or not. 
```
gdb) info source
Current source file is ../src/test.cpp
Compilation directory is /home/grifcj/.local/share/nvim/plugged/nvim-gdb/test/build
Located in /home/grifcj/.local/share/nvim/plugged/nvim-gdb/test/src/test.cpp
...
```
Workarounds are easy enough, though it may be nice to handle this case. I have travel for a couple weeks starting tomorrow, just letting you know cause my response or additional experimentation will likely be delayed for that time.

**Comment by sakhnik** [comment] 2020-01-13 09:46
@grifcj, thanks, that's very helpful. I also experienced this, ended up changing the current working directory to the build directory when debugging. Thus, the relative paths were enough to locate the files.
It doesn't seem too complicated to issue additional `info source` to lookup the paths. Probably, that's the way to investigate.

**Comment by Narice** [comment] 2020-01-13 10:38
@sakhnik sorry for the late response, I just tested it on my new minimal .vimrc and the results are quite strange. On one of my pc, it worked flawlessly, and on the other one, it doesn't work for certain projects.
For some of them, I get this error when trying to put a breakpoint:
![image](https://user-images.githubusercontent.com/31109099/72248270-0e388200-35f7-11ea-9b36-9f558ecfda38.png)
It seems to happen in cases where I get the error I posted before about synchronization.
I did :UpdateRemotePlugins but the error persists. The weirdest part is the fact that it works really well on my other pc. I have the exact same configuration.
I'm available during the following day for any following requests

**Comment by sakhnik** [comment] 2020-03-01 21:22
I've just discovered that `info source` will only output information about the current file being debugged. This is a bit too little for a user to open a random file and set a breakpoint in it.
So the real fix is to fix the build system, no other workaround. Nevertheless going to finish implementing `info source` for the best effort.

**Closed** 2020-03-03 08:02 UTC
Labels: question
